pull_request_rules:
  - name: automatic merge for master when CI passes and 1 reviews and not WIP
    conditions:
      - "#approved-reviews-by>=1"
      - check-success=codecov/patch
      - check-success=codecov/project
      - check-success=build (2.12.14)
      - check-success=build (2.13.6)
      - check-success=build (3.0.1)
      - base=master
      - label!=work-in-progress
    actions:
      merge:
        method: merge
        priority: high
  - name: automatic merge for master when CI passes and author is steward
    conditions:
      - author=scala-steward
      - check-success=codecov/patch
      - check-success=codecov/project
      - check-success=build (2.12.14)
      - check-success=build (2.13.6)
      - check-success=build (3.0.1)
      - base=master
    actions:
      merge:
        method: merge
        priority: medium
