name: CD

# triggers
on:
  workflow_run:
    workflows: ["CI"]
    branches: [main]
    tags: v[1-9]+.[0-9]+.[0-9]+
    types:
      - completed

# jobs
jobs:
  deploy:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        # supported scala versions
        scala:
          - 2.12.8
          - 2.13.4

    steps:
      - uses: actions/checkout@v2

      #----------- JDK -----------
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      #----------- CACHE -----------
      - name: Cache SBT
        uses: actions/cache@v2.1.4
        with:
          # A list of files, directories, and wildcard patterns to cache and restore
          path: |
            ~/.ivy2/cache
            ~/.sbt
          # An explicit key for restoring and saving the cache
          key: ${{ runner.os }}-sbt-${{ matrix.scala }}-${{ hashFiles('**/build.sb') }}

      #----------- RELEASE -----------
      - name: Release
        run: sbt clean compile ci-release

